---
# Source: keycloak-auth/templates/operatorgroup.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhbk-operator
spec:
  upgradeStrategy: Default
  targetNamespaces:
    - keycloak
