---
namespace: claw

resources:
  - namespace.yaml
  - rbac.yaml

helmCharts:
  - name: openclaw
    namespace: claw
    includeCRDs: false
    valuesFile: values.yaml
    version: 0.1.0
    releaseName: openclaw
    repo: https://eformat.github.io/helm-charts
