apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rhai-workshop-plugin.fullname" . }}-workshop-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rhai-workshop-plugin.labels" . | nindent 4 }}
data:
  tutorialUrls: |
    {{ .Values.tutorialUrls | toJson }}
