apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rhai-nav-plugin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rhai-nav-plugin.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rhai-nav-plugin.fullname" . }}-enabler
  labels:
    {{- include "rhai-nav-plugin.labels" . | nindent 4 }}
rules:
  - apiGroups: ["operator.openshift.io"]
    resources: ["consoles"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rhai-nav-plugin.fullname" . }}-enabler
  labels:
    {{- include "rhai-nav-plugin.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rhai-nav-plugin.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "rhai-nav-plugin.fullname" . }}-enabler
  apiGroup: rbac.authorization.k8s.io
