---
resources:
  - ../../base
  - namespace-imperative.yaml
  - kbsconfig.yaml
  - attestation.yaml
  - kbs-tls.yaml
  - resource-policy.yaml
  - eso.yaml
  - push-secret.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
