---
apiVersion: v1
kind: Namespace
metadata:
  name: chat
  metadata:
    labels:
      opendatahub.io/dashboard: 'true'
    annotations:
      openshift.io/description: 'Chat with an LLM'
      openshift.io/display-name: chat
