---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kuadrant-gateway-config
  namespace: mcp-test
data:
  gateway-name: mcp-gateway
  gateway-namespace: gateway-system
  hostname: test-mcp-server.mcp.local
  section-name: mcps
  prefix: k8s_
