---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mcp-weather
spec:
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: mcp-weather
    weight: 100
  wildcardPolicy: None
status: {}
