---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: rhoai-catalog-nightly
  namespace: openshift-marketplace
spec:
  displayName: RHOAI 3.4 Nightly
  grpcPodConfig:
    securityContextConfig: restricted
  image: quay.io/rhoai/rhoai-fbc-fragment:rhoai-3.4
  publisher: RHOAI Development Catalog
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 15m
