apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  annotations:
    alpha.maas.opendatahub.io/tiers: '["premium", "enterprise"]'
    opendatahub.io/hardware-profile-name: h200-priority
    opendatahub.io/hardware-profile-namespace: kimi-k25
    opendatahub.io/model-type: generative
    openshift.io/display-name: kimi-k2-5
    security.opendatahub.io/enable-auth: "true"
  labels:
    kueue.x-k8s.io/priority-class: high-priority
    kueue.x-k8s.io/queue-name: h200-priority
    opendatahub.io/dashboard: "true"
    opendatahub.io/genai-asset: "true"
  name: kimi-k2-5
  namespace: kimi-k25
spec:
  model:
    name: kimi-k2-5
    uri: pvc://data/kimi-k2-5
  replicas: 1
  router:
    gateway:
      refs:
      - name: maas-default-gateway
        namespace: openshift-ingress
    route: {}
  template:
    containers:
    - args:
      - --served-model-name={{.Name}}
      - --model=/mnt/models
      - --enable-ssl-refresh
      - --ssl-certfile=/var/run/kserve/tls/tls.crt
      - --ssl-keyfile=/var/run/kserve/tls/tls.key
      - --distributed-executor-backend=mp
      - --nnodes=1
      - --max-model-len=262144
      - --tensor-parallel-size=8
      - --pipeline-parallel-size=1
      - --trust-remote-code
      - --enable-auto-tool-choice
      - --tool-call-parser=kimi_k2
      - --mm-encoder-tp-mode=data
      - --enable-expert-parallel
      - --reasoning-parser=kimi_k2
      command:
      - python
      - -m
      - vllm.entrypoints.openai.api_server
      env:
      - name: TIKTOKEN_CACHE_DIR
        value: /tmp
      - name: VLLM_LOGGING_LEVEL
        value: DEBUG
      image: registry.redhat.io/rhaiis-preview/vllm-cuda-rhel9:voxtral-realtime
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /v1/models
          port: 8000
          scheme: HTTPS
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 10
      name: main
      readinessProbe:
        failureThreshold: 60
        httpGet:
          path: /v1/models
          port: 8000
          scheme: HTTPS
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      resources:
        limits:
          cpu: "8"
          memory: 128Gi
          nvidia.com/gpu: "8"
        requests:
          cpu: "8"
          memory: 128Gi
          nvidia.com/gpu: "8"
      startupProbe:
        failureThreshold: 360
        httpGet:
          path: /v1/models
          port: 8000
          scheme: HTTPS
        initialDelaySeconds: 30
        periodSeconds: 20
    tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
