---
apiVersion: v1
kind: Namespace
metadata:
  name: rhai-nav-plugin
---
apiVersion: v1
kind: Namespace
metadata:
  name: rhai-code-demo-plugin
---
apiVersion: v1
kind: Namespace
metadata:
  name: rhai-workshop-plugin
