# ---
# apiVersion: kueue.x-k8s.io/v1beta2
# kind: ResourceFlavor
# metadata:
#   name: "gpu-pool"
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: ClusterQueue
metadata:
  name: "cluster-queue"
spec:
  namespaceSelector: {} # match all.
  cohortName: unreserved
  preemption:
    borrowWithinCohort:
      maxPriorityThreshold: 100
      policy: LowerPriority
    reclaimWithinCohort: Any
    withinClusterQueue: Never
  resourceGroups:
  - coveredResources: ["cpu", "memory","nvidia.com/gpu"]
    flavors:
    - name: "gpu-pool"
      resources:
      - name: "cpu"
        nominalQuota: 0
      - name: "memory"
        nominalQuota: 0
      - name: "nvidia.com/gpu"
        nominalQuota: 0
  admissionChecksStrategy:
    admissionChecks:
    - name: multikueue-demo2
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: LocalQueue
metadata:
  namespace: "default"
  name: "user-queue"
spec:
  clusterQueue: "cluster-queue"
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: AdmissionCheck
metadata:
  name: multikueue-demo2
spec:
  controllerName: kueue.x-k8s.io/multikueue
  parameters:
    apiGroup: kueue.x-k8s.io
    kind: MultiKueueConfig
    name: multikueue-config-demo2
---
# OCM implements an Admissioncheck controller to automate the MultiKueue setup process.
# MultiKueueConfig is generated dynamically based on OCM placement decisions.
apiVersion: kueue.x-k8s.io/v1beta2
kind: AdmissionCheck
metadata:
  name: multikueue-config-demo2
spec:
  controllerName: open-cluster-management.io/placement
  parameters:
    apiGroup: cluster.open-cluster-management.io
    kind: Placement
    name: multikueue-config-demo2
