# Cluster proxy configuration
clusterProxy:
  url: "https://cluster-proxy-user.apps.sno.sandbox1763.opentlc.com"
  impersonation:
    enabled: false

networkPolicy:
  name: kueue-allow-egress-cluster-proxy-dns
  namespace: "openshift-kueue-operator"
  spec:
    podSelector:
      matchLabels:
        app.openshift.io/name: kueue
    policyTypes:
    - Egress
    egress:
    - ports:
      - port: 80
        protocol: TCP
    - ports:
      - port: 443
        protocol: TCP
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: multicluster-engine
