---
resources:
  - policy-operators.yaml
  - policy-argocd.yaml
  - policy-vault.yaml
  #- policy-gpu-node-label.yaml
  - policy-gateway.yaml
  - policy-aws-creds.yaml
  #- policy-cluster-autoscaler.yaml
  - policy-user-namespace-label.yaml
  - policy-storage-quota.yaml
  - policy-acm-clean.yaml
  - policy-ingresscontroller.yaml
