---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: netpol-spokes
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration, Rolling Restart - None  # None, Control, Compute, All
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: default-allow-all
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: networking.k8s.io/v1
                kind: NetworkPolicy
                metadata:
                  name: default-allow-all
                  namespace: openshift-config
                spec:
                  egress:
                  - {}
                  ingress:
                  - {}
                  podSelector: {}
                  policyTypes:
                  - Ingress
                  - Egress
          pruneObjectBehavior: DeleteIfCreated
          remediationAction: inform
          severity: high
  remediationAction: enforce
