---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-token
spec:
  refreshInterval: "1m0s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: openclaw-token
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: kv/data/ocp/sno/openshift-gitops/openclaw
      property: TOKEN
