apiVersion: v1
baseDomain: roadshow.$BASE_DOMAIN
compute:
- name: worker
  hyperthreading: Enabled
  replicas: 0
controlPlane:
  name: master
  replicas: 1
  architecture: amd64
  hyperthreading: Enabled
  platform:
    aws:
      type: g6.8xlarge
      rootVolume:
        size: 400
        type: gp3
metadata:
  name: hivec
platform:
  aws:
    region: us-east-2
    userTags:
      owner: "mhepburn@redhat.com"
      team: "global-labs"
      usage: "Dev"
      description: "Product Development and Demo environment for OpenShift"
sshKey: $SSH_PUBLIC_KEY
