---
apiVersion: v1
data:
  policy-notifier.py: |
    import requests
    import json
    import os
    import base64
    import urllib3
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

    CENTRAL = f"https://central"
    print(f">>> Creating auth token")
    ADMIN_PASSWD = base64.b64encode(f"admin:{os.environ.get('ROX_ADMIN_PASSWD')}".encode("ascii")).decode("ascii")
    HEADERS={"Authorization": f"Basic {ADMIN_PASSWD}", "Content-Type": "application/x-www-form-urlencoded", "Accept": "*/*"}
    DATA={"name": "policy-notifier", "role": "Admin"}

    auth = requests.post(
        f"{CENTRAL}/v1/apitokens/generate", data=json.dumps(DATA), headers=HEADERS, verify=False
    )
    print(auth.status_code)
    ROX_API_TOKEN = json.loads(auth.content)["token"]
    ROX_API_TOKEN_ID = json.loads(auth.content)["metadata"]["id"]

    # Fetching policies
    response = requests.get(f"{CENTRAL}/v1/policies", headers={"Authorization": f"Bearer {ROX_API_TOKEN}"}, verify=False)
    policies_data = response.json()
    policies = [policy['id'] for policy in policies_data['policies']]

    # Fetching notifiers
    response = requests.get(f"{CENTRAL}/v1/notifiers", headers={"Authorization": f"Bearer {ROX_API_TOKEN}"}, verify=False)
    notifiers_data = response.json()
    notifiers = [notifier['id'] for notifier in notifiers_data['notifiers']]

    # Finding splunk notifier
    splunk_notifier_id = None
    for notifier_id in notifiers:
        response = requests.get(f"{CENTRAL}/v1/notifiers/{notifier_id}", headers={"Authorization": f"Bearer {ROX_API_TOKEN}"}, verify=False)
        notifier_info = response.json()
        if notifier_info['type'] == "splunk":
            splunk_notifier_id = notifier_info['id']
            print(f">>> splunk notifier id: {splunk_notifier_id}")

    # Adding splunk notifier to policies
    for policy_id in policies:
        print(f">>> Adding splunk notifier to policyId: {policy_id}")
        notify_data = {
            "policyId": policy_id,
            "notifierIds": [splunk_notifier_id],
            "disable": False
        }
        with open('/tmp/notify.json', 'w') as f:
            json.dump(notify_data, f)
        response = requests.patch(f"{CENTRAL}/v1/policies/{policy_id}/notifiers", headers={"Authorization": f"Bearer {ROX_API_TOKEN}"}, data=open('/tmp/notify.json'), verify=False)
        print(response.status_code)  # Printing HTTP response code

    print(f">>> Removing auth token")
    response = requests.patch(f"{CENTRAL}/v1/apitokens/revoke/{ROX_API_TOKEN_ID}", headers={"Authorization": f"Bearer {ROX_API_TOKEN}"}, verify=False)
    print(response.status_code)

kind: ConfigMap
metadata:
  name: policy-notifier-script
  namespace: stackrox
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: acs-policy-notifier
  namespace: stackrox
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      name: acs-policy-notifier
    spec:
      template:
        spec:
          containers:
            - command:
                - /bin/bash
                - '-c'
                - |
                  #!/usr/bin/env bash
                  python -Wignore /opt/notifier/policy-notifier.py
              env:
                - name: ROX_ADMIN_PASSWD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: central-htpasswd
              image: registry.redhat.io/openshift4/ose-cli:latest
              imagePullPolicy: Always
              name: update-service-deploy
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /opt/notifier
                  name: notifier-script
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccountName: create-cluster-init
          terminationGracePeriodSeconds: 30
          volumes:
            - configMap:
                name: policy-notifier-script
              name: notifier-script
  schedule: "30 * * * *"
  successfulJobsHistoryLimit: 3
  suspend: false
