---
apiVersion: v1
kind: Namespace
metadata:
  name: stackrox
---
apiVersion: v1
kind: Namespace
metadata:
  name: rhacs-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhacs-operator-group
  namespace: rhacs-operator
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhacs-operator
  namespace: rhacs-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rhacs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: v1
data:
  admission-control-cert.pem: '{{hub fromSecret "openshift-gitops" "admission-control-tls" "admission-control-cert.pem" hub}}'
  admission-control-key.pem: '{{hub fromSecret "openshift-gitops" "admission-control-tls" "admission-control-key.pem" hub}}'
  ca.pem: '{{hub fromSecret "openshift-gitops" "admission-control-tls" "ca.pem" hub}}'
kind: Secret
metadata:
  name: admission-control-tls
  namespace: stackrox
type: Opaque
---
apiVersion: v1
data:
  collector-cert.pem: '{{hub fromSecret "openshift-gitops" "collector-tls" "collector-cert.pem" hub}}'
  collector-key.pem: '{{hub fromSecret "openshift-gitops" "collector-tls" "collector-key.pem" hub}}'
  ca.pem: '{{hub fromSecret "openshift-gitops" "collector-tls" "ca.pem" hub}}'
kind: Secret
metadata:
  name: collector-tls
  namespace: stackrox
type: Opaque
---
apiVersion: v1
data:
  sensor-cert.pem: '{{hub fromSecret "openshift-gitops" "sensor-tls" "sensor-cert.pem" hub}}'
  sensor-key.pem: '{{hub fromSecret "openshift-gitops" "sensor-tls" "sensor-key.pem" hub}}'
  ca.pem: '{{hub fromSecret "openshift-gitops" "sensor-tls" "ca.pem" hub}}'
  acs-host: '{{hub fromSecret "openshift-gitops" "sensor-tls" "acs-host" hub}}'
kind: Secret
metadata:
  name: sensor-tls
  namespace: stackrox
type: Opaque
---
apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  namespace: stackrox
  name: stackrox-secured-cluster-services
spec:
  clusterName: |
    {{ fromSecret "open-cluster-management-agent" "hub-kubeconfig-secret" "cluster-name" | base64dec }}
  auditLogs:
    collection: Auto
  centralEndpoint: |
    {{ fromSecret "stackrox" "sensor-tls" "acs-host" | base64dec }}
  admissionControl:
    listenOnCreates: false
    listenOnEvents: true
    listenOnUpdates: false
  # we tune these way down to save resources on the spoke cluster
  perNode:
    collector:
      collection: EBPF
      imageFlavor: Regular
      resources:
        limits:
          cpu: 500m
    taintToleration: TolerateTaints
    compliance:
      resources:
        limits:
          cpu: '1'
  scanner:
    analyzer:
      resources:
        limits:
          cpu: 1
    db:
      resources:
        limits:
          cpu: 1
  sensor:
    resources:
      limits:
        cpu: '1'
        memory: 1Gi
      requests:
        cpu: '1'
        memory: 4Gi
