---
apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: stackrox-secured-cluster-services
  namespace: stackrox
spec:
  clusterName: |
    {{ fromSecret "open-cluster-management-agent" "hub-kubeconfig-secret" "cluster-name" | base64dec }}
  auditLogs:
    collection: Auto
  centralEndpoint: |
    {{ fromSecret "stackrox" "sensor-tls" "acs-host" | base64dec }}
  admissionControl:
    listenOnCreates: false
    listenOnEvents: true
    listenOnUpdates: false
  scanner:
    scannerComponent: Disabled
  perNode:
    collector:
      collection: EBPF
      imageFlavor: Regular
    taintToleration: TolerateTaints
---
apiVersion: v1
data:
  admission-control-cert.pem: '{{ fromSecret "stackrox" "admission-control-tls" "admission-control-cert.pem" }}'
  admission-control-key.pem: '{{ fromSecret "stackrox" "admission-control-tls" "admission-control-key.pem" }}'
  ca.pem: '{{ fromSecret "stackrox" "admission-control-tls" "ca.pem" }}'
kind: Secret
metadata:
  labels:
    certificate_key_name: admission-control-cert.pem
  name: admission-control-tls
  namespace: openshift-gitops
type: Opaque
---
apiVersion: v1
data:
  collector-cert.pem: '{{ fromSecret "stackrox" "collector-tls" "collector-cert.pem" }}'
  collector-key.pem: '{{ fromSecret "stackrox" "collector-tls" "collector-key.pem" }}'
  ca.pem: '{{ fromSecret "stackrox" "collector-tls" "ca.pem" }}'
kind: Secret
metadata:
  labels:
    certificate_key_name: collector-cert.pem
  name: collector-tls
  namespace: openshift-gitops
type: Opaque
---
apiVersion: v1
data:
  sensor-cert.pem: '{{ fromSecret "stackrox" "sensor-tls" "sensor-cert.pem" }}'
  sensor-key.pem: '{{ fromSecret "stackrox" "sensor-tls" "sensor-key.pem" }}'
  ca.pem: '{{ fromSecret "stackrox" "sensor-tls" "ca.pem" }}'
  acs-host: '{{ fromSecret "stackrox" "sensor-tls" "acs-host" }}'
kind: Secret
metadata:
  labels:
    certificate_key_name: sensor-cert.pem
  name: sensor-tls
  namespace: openshift-gitops
type: Opaque
