---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
  name: create-cluster-init-bundle
  namespace: stackrox
spec:
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    spec:
      containers:
        - name: create-cluster-init-bundle
          image: registry.redhat.io/openshift4/ose-cli:latest
          imagePullPolicy: Always
          command:
          - /bin/bash
          - -c
          - |
            #!/usr/bin/env bash
            if kubectl get secret/sensor-tls &> /dev/null; then
              echo "cluster-init bundle has already been configured, doing nothing"
              exit 0
            else

              # Wait for central to be ready
              attempt_counter=0
              max_attempts=20
              echo "Waiting for central to be available..."
              until $(curl -k --output /dev/null --silent --head --fail https://central); do
                  if [ ${attempt_counter} -eq ${max_attempts} ];then
                    echo "Max attempts reached"
                    exit 1
                  fi

                  printf '.'
                  attempt_counter=$(($attempt_counter+1))
                  echo "Made attempt $attempt_counter, waiting..."
                  sleep 5
              done

              echo "Configuring cluster-init bundle"
              export DATA={\"name\":\"local-cluster\"}
              curl -k -o /tmp/bundle.json -X POST -u "admin:$PASSWORD" -H "Content-Type: application/json" --data $DATA https://central/v1/cluster-init/init-bundles

              echo "Bundle received"

              if [[ "$OSTYPE" == "linux-gnu"* ]]; then
                  BASE='base64 -w 0'
              elif [[ "$OSTYPE" == "darwin"* ]]; then
                  BASE='base64'
              fi

              echo "Applying bundle"
              if [[ $(grep "error" /tmp/bundle.json | wc -l) > "0" ]]; then
                echo "Bundle already created or errored ?..."
                exit 1
              fi            
              cat /tmp/bundle.json | python3 -c "import sys, json; print(json.load(sys.stdin)['kubectlBundle'])" | ${BASE} -d | oc apply -f -
              if [ $? != 0 ]; then
                echo "Error applying bundle ..."
                exit 1
              fi

              ACS_HOST="$(oc get route central -o custom-columns=HOST:.spec.host --no-headers):443"
              oc patch secret sensor-tls --type='json' -p="[{\"op\" : \"add\", \"path\" : \"/data/acs-host\", \"value\" : \"$(echo $ACS_HOST | ${BASE})\"}]"

              echo "ACS Cluster init bundle generated and applied"
            fi
          env:
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: central-htpasswd
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: create-cluster-init
      serviceAccountName: create-cluster-init
      terminationGracePeriodSeconds: 30
