---
apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: qwen3-cache-routing
  namespace: llama-serving
  labels:
    app.kubernetes.io/component: llm-inference
    app.kubernetes.io/name: qwen3-cache-routing
    app.kubernetes.io/instance: qwen3-cache-routing
    kueue.x-k8s.io/queue-name: default
    opendatahub.io/dashboard: "true"
    opendatahub.io/genai-asset: "true"
  annotations:
    security.opendatahub.io/enable-auth: "true"
spec:
  model:
    uri: oci://registry.redhat.io/rhelai1/modelcar-qwen3-8b-fp8-dynamic:latest
    name: RedHatAI/Qwen3-8B-FP8-dynamic
  # Two replicas to demonstrate KV cache routing across instances
  replicas: 2
  router:
    scheduler:
      template:
        affinity:
          podAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - qwen3-cache-routing
              topologyKey: "kubernetes.io/hostname"
        volumes:
        - emptyDir: { }
          name: tokenizers
        containers:
          - name: main
            volumeMounts:
              - mountPath: /mnt/tokenizers
                name: tokenizers
                readOnly: false
            args:
              - --pool-name
              - "{{ ChildName .ObjectMeta.Name `-inference-pool` }}"
              - --pool-namespace
              - "{{ .ObjectMeta.Namespace }}"
              - --pool-group
              - inference.networking.x-k8s.io
              - --zap-encoder
              - json
              - --grpc-port
              - "9002"
              - --grpc-health-port
              - "9003"
              - --secure-serving
              - --model-server-metrics-scheme
              - https
              - --model-server-metrics-https-insecure-skip-verify
              - --cert-path
              - /var/run/kserve/tls
              - --config-text
              - |
                apiVersion: inference.networking.x-k8s.io/v1alpha1
                kind: EndpointPickerConfig
                plugins:
                - type: single-profile-handler
                - type: prefix-cache-scorer
                  parameters:
                    mode: cache_tracking  # Real-time KV cache tracking via ZMQ events
                    indexerConfig:
                      tokenProcessorConfig:
                        blockSize: 64       # Must match vLLM --block-size (default is 16)
                        hashSeed: "42"      # Must match PYTHONHASHSEED in vLLM pods
                      kvBlockIndexConfig:
                        enableMetrics: true                   # Enable Prometheus metrics for KV cache index
                        metricsLoggingInterval: 60000000000   # Log metrics every 60 seconds (in nanoseconds)
                      tokenizersPoolConfig:
                        tokenizersCacheDir: /mnt/tokenizers
                - type: load-aware-scorer
                - type: max-score-picker
                schedulingProfiles:
                  - name: default
                    plugins:
                      - pluginRef: prefix-cache-scorer
                        weight: 2.0
                      - pluginRef: load-aware-scorer
                        weight: 1.0
                      - pluginRef: max-score-picker
    route: { }
    gateway: { }
  template:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - weight: 50
          labelSelector:
            matchExpressions:
            - key: kserve.io/component
              operator: In
              values:
              - workload
          topologyKey: "kubernetes.io/hostname"
    containers:
      - name: main
        env:
          # Configure vLLM for prefix caching with KV cache event publishing
          - name: VLLM_ADDITIONAL_ARGS
            value: "--prefix-caching-hash-algo sha256 --block-size 64 --kv_transfer_config '{\"kv_connector\":\"NixlConnector\",\"kv_role\":\"kv_both\"}' --kv-events-config '{\"enable_kv_cache_events\":true,\"publisher\":\"zmq\",\"endpoint\":\"tcp://{{ ChildName .ObjectMeta.Name `-epp-service` }}:5557\",\"topic\":\"kv@${POD_IP}@RedHatAI/Qwen3-8B-FP8-dynamic\"}'"
          # Pod IP used in KV cache event topic
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          # Hash seed must match scheduler configuration
          - name: PYTHONHASHSEED
            value: "42"
        resources:
          limits:
            cpu: '1'
            memory: 8Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: '1'
            memory: 8Gi
            nvidia.com/gpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 5
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qwen3-cache-routing
  namespace: llama-serving
---
apiVersion: v1
kind: Secret
metadata:
  name: qwen3-cache-routing-qwen3-cache-routing
  namespace: llama-serving
  annotations:
    kubernetes.io/service-account.name: "qwen3-cache-routing"
    openshift.io/display-name: qwen3-cache-routing
  labels:
    opendatahub.io/dashboard: "true"
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    opendatahub.io/dashboard: "true"
  name: qwen3-cache-routing-view-role
  namespace: llama-serving
rules:
- apiGroups:
  - serving.kserve.io
  resourceNames:
  - qwen3-cache-routing
  resources:
  - llminferenceservices
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    opendatahub.io/dashboard: "true"
  name: qwen3-cache-routing-view
  namespace: llama-serving
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: qwen3-cache-routing-role
subjects:
- kind: ServiceAccount
  name: qwen3-cache-routing
