---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-peer-pods-secret-spokes
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-spoke-coco
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: peer-pods-secret-spokes
