# oc kustomize https://github.com/opendatahub-io/models-as-a-service//deployment/overlays/openshift?ref=39e62e98f382621e401211ae21cb9de0601b8266
---
apiVersion: v1
kind: Namespace
metadata:
  name: maas-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: maas-api
    app.kubernetes.io/part-of: models-as-a-service
  name: maas-api
  namespace: maas-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: maas-api
    app.kubernetes.io/part-of: models-as-a-service
  name: maas-api
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - serving.kserve.io
  resources:
  - inferenceservices
  - llminferenceservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: maas-api
    app.kubernetes.io/part-of: models-as-a-service
  name: maas-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: maas-api
subjects:
- kind: ServiceAccount
  name: maas-api
  namespace: maas-api
---
apiVersion: v1
data:
  tiers: |
    # Free tier - default for all authenticated users
    - name: free
      displayName: Free Tier
      level: 0
      groups:
        - tier-free-users
        - system:authenticated  # Default for all authenticated users

    # Premium tier - for premium users
    - name: premium
      displayName: Premium Tier
      level: 1
      groups:
        - tier-premium-users
        - premium-group

    # Enterprise tier - highest level
    - name: enterprise
      displayName: Enterprise Tier
      level: 2
      groups:
        - tier-enterprise-users
        - enterprise-group
        - admin-group
kind: ConfigMap
metadata:
  labels:
    app: maas-api
    app.kubernetes.io/component: api
    app.kubernetes.io/name: maas-api
    app.kubernetes.io/part-of: models-as-a-service
    component: tier-mapping
  name: tier-to-group-mapping
  namespace: maas-api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: maas-api
    app.kubernetes.io/part-of: models-as-a-service
  name: maas-api
  namespace: maas-api
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: maas-api
    app.kubernetes.io/part-of: models-as-a-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: maas-api
    app.kubernetes.io/part-of: models-as-a-service
  name: maas-api
  namespace: maas-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/name: maas-api
      app.kubernetes.io/part-of: models-as-a-service
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api
        app.kubernetes.io/name: maas-api
        app.kubernetes.io/part-of: models-as-a-service
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/opendatahub/maas-api:latest-0681979
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        name: maas-api
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: maas-api
      terminationGracePeriodSeconds: 30
---
apiVersion: extensions.kuadrant.io/v1alpha1
kind: TelemetryPolicy
metadata:
  labels:
    app.kubernetes.io/part-of: maas-observability
  name: user-group
  namespace: openshift-ingress
spec:
  metrics:
    default:
      labels:
        model: responseBodyJSON("/model")
        tier: auth.identity.tier
        user: auth.identity.userid
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: maas-default-gateway
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: openshift-default
spec:
  controllerName: openshift.io/gateway-controller/v1
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    opendatahub.io/managed: "false"
  labels:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: maas-default-gateway
    app.kubernetes.io/name: maas
    opendatahub.io/managed: "false"
  name: maas-default-gateway
  namespace: openshift-ingress
spec:
  gatewayClassName: openshift-default
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    hostname: maas.apps.roadshow-6kr2w.sandbox1763.opentlc.com
    name: http
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: All
    hostname: maas.apps.roadshow-6kr2w.sandbox1763.opentlc.com
    name: https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: default-ingress-cert
      mode: Terminate
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: maas-api
    app.kubernetes.io/part-of: models-as-a-service
  name: maas-api-route
  namespace: maas-api
spec:
  parentRefs:
  - name: maas-default-gateway
    namespace: openshift-ingress
  rules:
  - backendRefs:
    - name: maas-api
      port: 8080
      weight: 100
    matches:
    - path:
        type: PathPrefix
        value: /v1/models
  - backendRefs:
    - name: maas-api
      port: 8080
      weight: 100
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          replacePrefixMatch: /
          type: ReplacePrefixMatch
    matches:
    - path:
        type: PathPrefix
        value: /maas-api
---
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: maas-api
    app.kubernetes.io/part-of: models-as-a-service
  name: maas-api-auth-policy
  namespace: maas-api
spec:
  rules:
    authentication:
      openshift-identities:
        kubernetesTokenReview:
          audiences:
          - https://kubernetes.default.svc
          - maas-default-gateway-sa
    response:
      success:
        headers:
          X-MaaS-Group:
            plain:
              selector: auth.identity.user.groups.@tostr
          X-MaaS-Username:
            plain:
              selector: auth.identity.user.username
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: maas-api-route
---
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: gateway-auth-policy
  namespace: openshift-ingress
spec:
  rules:
    authentication:
      service-accounts:
        cache:
          key:
            selector: context.request.http.headers.authorization.@case:lower
          ttl: 600
        defaults:
          userid:
            expression: |
              auth.identity.user.username.split(":")[3]
        kubernetesTokenReview:
          audiences:
          - maas-default-gateway-sa
    authorization:
      tier-access:
        cache:
          key:
            selector: '{auth.identity.user.username}:{request.path}'
          ttl: 60
        kubernetesSubjectAccessReview:
          authorizationGroups:
            expression: auth.identity.user.groups
          resourceAttributes:
            group:
              value: serving.kserve.io
            name:
              expression: |
                request.path.split("/")[2]
            namespace:
              expression: |
                request.path.split("/")[1]
            resource:
              value: llminferenceservices
            verb:
              value: post
          user:
            expression: auth.identity.user.username
    metadata:
      matchedTier:
        cache:
          key:
            selector: auth.identity.user.username
          ttl: 300
        http:
          body:
            expression: '{ "groups": auth.identity.user.groups }'
          contentType: application/json
          method: POST
          url: http://maas-api.maas-api.svc.cluster.local:8080/v1/tiers/lookup
    response:
      success:
        filters:
          identity:
            json:
              properties:
                tier:
                  expression: auth.metadata.matchedTier["tier"]
                userid:
                  expression: auth.identity.userid
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: maas-default-gateway
---
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: gateway-rate-limits
  namespace: openshift-ingress
spec:
  limits:
    enterprise:
      counters:
      - expression: auth.identity.userid
      rates:
      - limit: 50
        window: 2m
      when:
      - predicate: |
          auth.identity.tier == "enterprise"
    free:
      counters:
      - expression: auth.identity.userid
      rates:
      - limit: 5
        window: 2m
      when:
      - predicate: |
          auth.identity.tier == "free"
    premium:
      counters:
      - expression: auth.identity.userid
      rates:
      - limit: 20
        window: 2m
      when:
      - predicate: |
          auth.identity.tier == "premium"
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: maas-default-gateway
---
apiVersion: kuadrant.io/v1alpha1
kind: TokenRateLimitPolicy
metadata:
  name: gateway-token-rate-limits
  namespace: openshift-ingress
spec:
  limits:
    enterprise-user-tokens:
      counters:
      - expression: auth.identity.userid
      rates:
      - limit: 100000
        window: 1m
      when:
      - predicate: |
          auth.identity.tier == "enterprise"
    free-user-tokens:
      counters:
      - expression: auth.identity.userid
      rates:
      - limit: 100
        window: 1m
      when:
      - predicate: |
          auth.identity.tier == "free"
    premium-user-tokens:
      counters:
      - expression: auth.identity.userid
      rates:
      - limit: 50000
        window: 1m
      when:
      - predicate: |
          auth.identity.tier == "premium"
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: maas-default-gateway
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: limitador
    app.kubernetes.io/part-of: maas-observability
  name: limitador-metrics
  namespace: kuadrant-system
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: http
  selector:
    matchLabels:
      app: limitador
