---
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
  name: gateway-rate-limits
  namespace: openshift-ingress
spec:
  limits:
    enterprise:
      counters:
      - expression: auth.identity.userid
      rates:
      - limit: 50
        window: 2m
      when:
      - predicate: |
          auth.identity.tier == "enterprise"
    free:
      counters:
      - expression: auth.identity.userid
      rates:
      - limit: 5
        window: 2m
      when:
      - predicate: |
          auth.identity.tier == "free"
    premium:
      counters:
      - expression: auth.identity.userid
      rates:
      - limit: 20
        window: 2m
      when:
      - predicate: |
          auth.identity.tier == "premium"
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: maas-default-gateway
---
apiVersion: kuadrant.io/v1alpha1
kind: TokenRateLimitPolicy
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
  name: gateway-token-rate-limits
  namespace: openshift-ingress
spec:
  limits:
    enterprise-user-tokens:
      counters:
      - expression: auth.identity.userid
      rates:
      - limit: 100000
        window: 1m
      when:
      - predicate: |
          auth.identity.tier == "enterprise"
    free-user-tokens:
      counters:
      - expression: auth.identity.userid
      rates:
      - limit: 100
        window: 1m
      when:
      - predicate: |
          auth.identity.tier == "free"
    premium-user-tokens:
      counters:
      - expression: auth.identity.userid
      rates:
      - limit: 50000
        window: 1m
      when:
      - predicate: |
          auth.identity.tier == "premium"
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: maas-default-gateway
