apiVersion: v1
data:
  certificates-spoke.sh: |
    #!/bin/bash

    ACME_STAGING=${ACME_STAGING:-}
    ACME_SERVER=https://acme-v02.api.letsencrypt.org/directory
    HOSTED_ZONE=${HOSTED_ZONE:-}
    AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}

    if [ ! -z "${ACME_STAGING}" ]; then
        ACME_SERVER=https://acme-staging-v02.api.letsencrypt.org/directory
    fi

    create_aws_secrets() {
        echo "🌴 Running create_aws_secrets..."

        oc get secret aws-creds -n kube-system -o yaml | sed 's/namespace: .*/namespace: openshift-config/' | oc -n openshift-config apply -f-
        oc get secret aws-creds -n kube-system -o yaml | sed 's/namespace: .*/namespace: openshift-ingress/' | oc -n openshift-ingress apply -f-
        export AWS_ACCESS_KEY_ID=$(oc get secret aws-creds -n kube-system -o template='{{index .data "aws_access_key_id"}}' | base64 -d)
        if [ "$?" != 0 ]; then
            echo -e "Failed - to find aws_access_key_id ?"
        fi

        echo "🌴 create_aws_secrets ran OK"
    }
kind: ConfigMap
metadata:
  name: cert-init
  namespace: openshift-config
