apiVersion: v1
data:
  certificates-spoke.sh: |-
    #!/bin/bash

    ACME_STAGING=${ACME_STAGING:-}
    ACME_SERVER=https://acme-v02.api.letsencrypt.org/directory
    HOSTED_ZONE=${HOSTED_ZONE:-}
    AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
kind: ConfigMap
metadata:
  name: cert-init
  namespace: openshift-config
