---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: oauth-htpasswd
  annotations:
    policy.open-cluster-management.io/categories: AC Access Control
    policy.open-cluster-management.io/controls: AC-3 Access Enforcement
    policy.open-cluster-management.io/standards: NIST SP 800-53
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: oauth-htpasswd-secret
        spec:
          object-templates-raw: |
            {{- if not (lookup "v1" "ConfigMap" "openshift-config" "prelude") }}
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: v1
                data:
                  htpasswd: YWRtaW46JDJ5JDA1JGQ4YkcxeC9ONmFsS3FqaWtTSGcwNE9yeG56QkQ0a0h5NldEVHhHY0p3TTF5SFRnbWsxRTAuCnVzZXIxOiQyeSQwNSRQLi5BSnpENFkwNElHaFVIWmV3MmJPWFpvdFJCTDJielBsaXpTVjVzSFRKejdiNzJhcTNqVwp1c2VyMjokMnkkMDUkV1U3bnhBVFNuZ0lnRTFMMWRiY0tEZS9lWGcvUkRwb3o0V3RwOGM1NVluN2ZyalpkVUhySi4K
                kind: Secret
                metadata:
                  name: htpass-secret
                  namespace: openshift-config
                type: Opaque
            {{- end }}
          pruneObjectBehavior: None
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: oauth-roadshow
        spec:
          object-templates-raw: |
            {{- if not (lookup "v1" "ConfigMap" "openshift-config" "prelude") }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: OAuth
                metadata:
                  name: cluster
                spec:
                  identityProviders:
                    - name: roadshow
                      htpasswd:
                        fileData:
                          name: htpass-secret
                      mappingMethod: claim
                      type: HTPasswd
            {{- end }}
          pruneObjectBehavior: DeleteIfCreated
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: oauth-prelude
        spec:
          object-templates-raw: |
            {{- if (lookup "v1" "ConfigMap" "openshift-config" "prelude") }}
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: OAuth
                metadata:
                  name: cluster
                spec:
                  identityProviders:
                    - name: prelude
                      htpasswd:
                        fileData:
                          name: htpass-secret
                      mappingMethod: claim
                      type: HTPasswd
            {{- end }}
          pruneObjectBehavior: DeleteIfCreated
          remediationAction: inform
          severity: high
  remediationAction: enforce
